# Generated by Django 4.2.7 on 2023-11-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='cover.jpg', upload_to='cover_pics'),
        ),
    ]
